# Generated by Django 2.2.7 on 2019-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(max_length=120),
        ),
    ]
