# Generated by Django 2.2.7 on 2019-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191201_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
