# Generated by Django 2.2.7 on 2019-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191107_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
