// User
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_ERROR = "USER_ERROR";

// WALLETS
export const GET_WALLETS = "GET_WALLETS";
export const WALLET_LOADING = "WALLET_LOADING";
export const WALLETS_ERROR = "WALLETS_ERROR";
export const ADD_WALLET = "ADD_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";
export const WALLET_CURRENT = "WALLET_CURRENT";
export const WALLET_CLEAR_CURRENT = "WALLET_CLEAR_CURRENT";
export const UPDATE_WALLET = "UPDATE_WALLET";
export const SEARCH_WALLETS = "SEARCH_WALLETS";

// Operations
export const GET_OPERATIONS = "GET_OPERATIONS";
export const OPERATION_LOADING = "OPERATION_LOADING";
export const OPERATIONS_ERROR = "OPERATIONS_ERROR";
export const ADD_OPERATION = "ADD_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const OPERATION_CURRENT = "OPERATION_CURRENT";
export const OPERATION_CLEAR_CURRENT = "OPERATION_CLEAR_CURRENT";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const SEARCH_OPERATIONS = "SEARCH_OPERATIONS";

// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth
export const REMIND_ME = "REMIND_ME";
export const AUTH_START = "AUTH_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTHLOGOUTT";
