// User
export const GET_USER = "GET_USER";
export const USER_LOADING = "OPERATION_LOADING";
export const USER_ERROR = "USER_ERROR";

// Operations
export const GET_OPERATIONS = "GET_OPERATIONS";
export const OPERATION_LOADING = "OPERATION_LOADING";
export const OPERATIONS_ERROR = "OPERATIONS_ERROR";
export const ADD_OPERATION = "ADD_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const OPERATION_CURRENT = "OPERATION_CURRENT";
export const OPERATION_CLEAR_CURRENT = "OPERATION_CLEAR_CURRENT";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const SEARCH_OPERATIONS = "SEARCH_OPERATIONS";

// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth
export const REMIND_ME = "REMIND_ME";
export const AUTH_START = "AUTH_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTHLOGOUTT";
