# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-11 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
    ]
