# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20191011_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
