# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20191011_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
