# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='addToAmount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='removeFromAmount',
            field=models.BooleanField(default=True),
        ),
    ]
