# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20191012_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='addToAmount',
        ),
    ]
